#!/bin/bash
#SBATCH --partition=main           # Partition (job queue)
#SBATCH --job-name relax           # Assign a name to the job
#SBATCH --nodes=1                  # Number of nodes
#SBATCH --ntasks=1                 # Number of tasks (usually = cores) on each node
#SBATCH --mem=200                  # Real memory required (MB)
#SBATCH --time=3-00:00:00          # Total run time limit (HH:MM:SS)
#SBATCH --output=slurm.%N.%j.out   # STDOUT output file
#SBATCH --error=slurm.%N.%j.out    # STDERR output file
#SBATCH --export=ALL               # Export you current env to the job env

while (( $# > 1 ))
do
    case $1 in
        # -pr) protein_database="$2";; # i.e. proteins
        -nchains) n_chains="$2";; # i.e. 1 or 2
        -pos) position_file_wildcard="$2";; # i.e. *_F*_C*, optional
        -lig) ligand_path="$2";; # i.e. ligands/O2beY-CYS
        -n) decoys="$2";; # optional
        -mem) memory="$2";; # optional
        *) break;
    esac
    shift 2
done

if ! [ -z "${position_file_wildcard}" ]
then
    position_file_wildcard=*"_"*"_"*
fi

if ! [ -z "${decoys}" ]
then
    decoys="-n "${decoys}
else
    decoys="-n 100"
fi

if [ -z "${memory}" ]
then
    memory="2000"
fi

params_files="-params"
for params_file in `ls ${ligand_path}/*.params`
do
    params_files=${params_files}" ../../../../"${params_file}
done

ligand=${ligand_path##*/}

case ${ligand_path##*-} in
    ASP)
        nucleophile_name3=ASX
        ;;
    GLU)
        nucleophile_name3=GLX
        ;;
    CYS)
        nucleophile_name3=CYX
        ;;
    HIS)
        nucleophile_name3=HIX
        ;;
    LYS)
        nucleophile_name3=LYX
        ;;
esac

for subdir in antibody
do
# mkdir "out"${subdir}
cd "out"${subdir}
for protein in `ls`; do
    cd ${protein}
    for protein_chain_ligand in `ls`; do
        if ([[ ${n_chains} == 1 ]] && [[ ${protein_chain_ligand} != *"-"*"-"*"_"${ligand} ]]) || ([[ ${n_chains} == 2 ]] && [[ ${protein_chain_ligand} == *"-"*"-"*"_"${ligand} ]]); then
            rm ${protein_chain_ligand}/*.log ${protein_chain_ligand}/*.err
            if [ -z "$(ls -A ${protein_chain_ligand})" ]; then
                rm -r ${protein_chain_ligand}
                continue
            fi
            # for symmetry in `ls ../../pdb${subdir}/${protein}/*.symm`
            # do
            #     symmetry="-symm ../../"${symmetry}
            #     break
            # done
            cd ${protein_chain_ligand}
            for variant in `ls`
            do
                if [ -d ${variant} ] && [[ ${variant} == ${protein}"-"* ]] && [[ ${variant} == ${position_file_wildcard} ]]
                then
                    if [ -z "$(ls -A ${variant})" ]; then
                        rm -r ${variant}
                        continue
                    fi
                    cd ${variant}
                    run_unbound=false
                    for pdb_input in `ls *.pdb`
                    do
                        if [[ ${pdb_input} == "Z"*"X"*"-unbound.pdb" ]]
                        then
                            run_unbound=true
                        fi
                    done
                    for pdb_input in `ls *.pdb`
                    do
                        if ${run_unbound} && [[ ${pdb_input} == "Z"*"X"*".pdb" ]] && [[ ${pdb_input} != *"-unbound.pdb" ]]
                        then
                            while [ $(squeue -u zs251 | wc -l) -ge 500 ]
                            do
                                sleep 180;
                            done
                            slurmit.py --job ${variant} --mem ${memory} --time 3-00:00:00 --command \
                                "python ../../../../../enzdes_utils/fast_design.py ${pdb_input:0:-4}-unbound.pdb \
                                -ref ../../../../pdb${subdir}/${protein}/${variant%%_*}-unbound.pdb \
                                -index_ref ${pdb_input} ${params_files} ${symmetry} -sf ref2015_cst \
                                -cat_ids TYZ ${nucleophile_name3} -sub_ids OBY \
                                -rpk_nbh -min_nbh -n 10 -save_n 1 -prefix ${variant}-unbound;"
                            slurmit.py --job ${variant} --mem ${memory} --time 3-00:00:00 --command \
                                "python ../../../../../enzdes_utils/fast_design.py \
                                ../../../../pdb${subdir}/${protein}/${variant%%_*}-unbound_relaxed.pdb \
                                -ref ../../../../pdb${subdir}/${protein}/${variant%%_*}-unbound.pdb \
                                -index_ref ${pdb_input} ${params_files} ${symmetry} -sf ref2015_cst \
                                -cat_ids TYZ ${nucleophile_name3} -sub_ids OBY \
                                -ddG_wt -rpk_nbh -min_nbh -n 10 -save_n 1 -prefix ${variant%%_*}-unbound_apo;"
                            break
                        fi
                    done
                    cd ..
                    sleep 0.05
                fi
            done
            cd ..
        fi
    done
    cd ..
done
cd ..
done
